# Generated by Django 4.2.11 on 2024-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('gitHub', models.CharField(max_length=20)),
            ],
        ),
    ]
